export const STORAGE_VERSION = '1';

export const BOOK_LIST_KEY = `VELOREAD_BOOK_LIST_V${STORAGE_VERSION}`;
export const GLOBAL_SETTINGS_KEY = `VELOREAD_GLOBAL_SETTINGS_V${STORAGE_VERSION}`;
export const READING_STATE_PREFIX = `VELOREAD_READING_STATE_V${STORAGE_VERSION}_`;
export const TOKEN_CHUNK_PREFIX = `VELOREAD_BOOK_TOKENS_V${STORAGE_VERSION}_`;

export const DEFAULT_CHUNK_SIZE = 500;
export const DEFAULT_WPM = 320;
